#
# $FreeBSD$
#

MAN=	audit.2								\
	auditctl.2							\
	auditon.2							\
	getaudit.2							\
	getauid.2							\
	setaudit.2							\
	setauid.2							\
	audit_class.5							\
	audit_control.5							\
	audit_event.5							\
	audit_user.5							\
	audit_warn.5

.include <bsd.prog.mk>
